[book]
title = "Rust con ejemplos"
description = "Rust con ejemplos es una colección de ejemplos ejecutables que ilustran varios conceptos y bibliotecas estándar de Rust."
author = "La Comunidad Rust"

[output.html.playpen]
editable = true
editor = "ace"

[output.html.fold]
enable = true
